platform :ios, '9.0'
target 'HaiTang' do
  pod 'MJExtension'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'AFNetworking', '4.0'
  pod 'IQKeyboardManager'
  pod 'WMPageController', '2.5.2'
  pod 'JYUtils'                    #UI库
  pod 'SDCycleScrollView', '1.80'
  pod 'YYKit'


end
